### ISSUE TITLE
Defaultní kvalita

### ISSUE THREAD

**Issue by ondrakoupil** [MichaelPavlista/palette#1]
Ahoj,

tak jsem doporučil na jeden projekt známým používat Palette, a narazili jsme na drobnost, která by ale dost pomohla :-)

Defaultní kvalita JPG obrázků je nastavena na 100 a nikde není zdokumentovaná možnost snížit kvalitu výstupního obrázku pomocí Quality filtru. Totéž progresivní obrázky a Progressive filtr. Ve výsledku pak Palette generuje veliké soubory se 100% kvalitou, což je často zbytečné. Běžný laik vývojář ani neví, že má možnost to změnit. Co změnit default kvalitu třeba na 80 nebo 85, to je tak akorát, a přidat do dokumentace zmínku o možnosti ji nastavit?

Díky a zdravím,

OK.

**Comment by MichaelPavlista** [comment]
Ahoj Ondro,
komentáře jsem si bohužel všimnul až teď (notifikace mi někde zapadla).

Požadavek určitě dává smysl a kouknu se na něj co nejdříve :).

M
