### ISSUE TITLE
Nelze zadat parametr filtru s tečkou

### ISSUE THREAD

**Issue by dav281** [MichaelPavlista/palette#5]
Nelze vydefinovat filtr, který má v parametru tečku,
konkrétně je to problém například pokud se použije filter Watermark, který jako první parametr přijímá cestu k obrázku

` <img src="{$product->mainPhoto|palette:"Watermark;logo.png"}"/>`

Při parsování parametrů a selekci filtrů, které se mají aplikovat systém chybně vyhodnotí koncovku .png jako další filtr a vyhodí výjímku, protože .png není žádný filtr

![image](https://user-images.githubusercontent.com/9195437/82932313-81300d00-9f88-11ea-81df-11123e7d91b9.png)

Základní použité prostředí:
- php 7.4.3
- nette 3.0
- pavlista/nette-palette: 2.0.1

**Comment by MichaelPavlista** [comment]
Ahoj,
vydal jsem opravu k otestování.

**Pro její použití:**
1) Do composer.json přidej/uprav `"pavlista/palette": "dev-issue_5_template_bug as 2.7.4"`
2) V projektu aktualizuj balíček přes `composer update pavlista/palette`

Pokud bude i za tebe všechno v pořádku, vydám novou ostrou verzi balíčku :).

Předem díky,
Michael

**Comment by dav281** [comment]
Ahoj,
odzkoušeno, parametry se již parsují správně
