### ISSUE TITLE
Watermark filter volá Product() s null parameterm, chybí ošetření na NULL

### ISSUE THREAD

**Issue by dav281** [MichaelPavlista/palette#7]
Watermark filter volá druhý parametr IPictureGenerator $pictureGenerator s příznakem NULL, následně v kodu se snaží kod nad tímto parametrem zavolat funkci.

Navrhuji ošetření `$defaultQuality = $pictureGenerator ? $pictureGenerator->getDefaultQuality(); : 90`

![image](https://user-images.githubusercontent.com/9195437/83018028-ec2f2180-a024-11ea-85ee-9a0720860118.png)

**Comment by dav281** [comment]
V případě, když si v kodu přepíšu funkci `getDefaultQuality()` na jakékoliv číslo, tak se vodoznak vloží a funguje

**Comment by MichaelPavlista** [comment]
Ahoj,
mělo by to být již OK.

V kódu se nyní kontroluje existence služby IPictureGenerator a v efektu Watermark je nastavená kvalita obrázku vždy na 100% (jiná hodnota by zde nedávala smysl jelikož se obrázek vodoznaku vloží do hlavního obrázku a při uložení se použije jeho definovaná kvalita :)).

Michael
